version: '3.8'
services:
  backend:
    build:
      context: ./TeamCalendar
      dockerfile: Dockerfile
    container_name: teamcalendar_nestjs
    ports:
      - "5000:5000"  
    environment:
      NODE_ENV: production
      DB_HOST: mysql  
      DB_USER: user  
      DB_PASSWORD: userpassword  
      DB_NAME: teamcalendar  
    depends_on:
      - mysql 
  mysql:
  image: mysql:5.7
  container_name: teamcalendar_mysql
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: teamcalendar
    MYSQL_USER: user
    MYSQL_PASSWORD: userpassword
  ports:
    - "3306:3306"
  volumes:
    - mysql-data:/var/lib/mysql
      
  frontend:
    build:
      context: ./calendar-react
      dockerfile: Dockerfile
    container_name: teamcalendar_react
    ports:
      - "80:80"  
    environment:
      NODE_ENV: production
    depends_on:
      - backend  
 
volumes:
  mysql-data:
   